const residenceData = 
[
    {
        id:1,
        img: '/Images/Residence/img1.webp',
        icon:'fa-solid fa-dollar',
        price:'47,043',
        title:'Aliva Priva Jardin',
        address:'12, Orchid Apartments, Banjara Hills, Hyderabad, Telangana 500034',
    },
    {
        id:2,
        img: '/Images/Residence/img2.webp',
        icon:'fa-solid fa-dollar',
        price:'49,126',
        title:'Whispering Pines Cottage',
        address:'23, Shanti Vihar Colony, Rajendra Nagar, Lucknow, Uttar Pradesh',
    },
    {
        id:3,
        img: '/Images/Residence/img3.webp',
        icon:'fa-solid fa-dollar',
        price:'56,081',
        title:'Sunnybrook Villa',
        address:'45, Green Park Extension, Outer Ring Road, New Delhi, Delhi',
    },
    {
        id:4,
        img: '/Images/Residence/img4.webp',
        icon:'fa-solid fa-dollar',
        price:'51,117',
        title:'Maplewood Haven',
        address:'128, Silver Oak Apartments, MG Road, Pune, Maharashtra',
    },
    {
        id:5,
        img: '/Images/Residence/img5.webp',
        icon:'fa-solid fa-dollar',
        price:'63,601',
        title:'Willow Creek House',
        address:'56, Royal Residency, Bannerghatta Road, Bengaluru, Karnataka',
    },
    {
        id:6,
        img: '/Images/Residence/img6.webp',
        icon:'fa-solid fa-dollar',
        price:'59,011',
        title:'Rosewood Retreat',
        address:'78, Rose Villa, Ambattur Industrial Estate, Chennai, Tamil Nadu',
    },
    {
        id:7,
        img: '/Images/Residence/img7.webp',
        icon:'fa-solid fa-dollar',
        price:'48,512',
        title:'Birchwood Bungalow',
        address:'90, Sunshine Apartments, Gariahat Road, Kolkata, West Bengal',
    },
    {
        id:8,
        img: '/Images/Residence/img8.webp',
        icon:'fa-solid fa-dollar',
        price:'67,451',
        title:'Oakwood Manor',
        address:'67, Harmony Enclave, Jubilee Hills, Hyderabad, Telangana',
    },
    {
        id:9,
        img: '/Images/Residence/img9.webp',
        icon:'fa-solid fa-dollar',
        price:'57,341',
        title:'Honeysuckle House',
        address:'89, Coral Villas, Marine Drive, Kochi, Kerala',
    },
    {
        id:10,
        img: '/Images/Residence/img10.webp',
        icon:'fa-solid fa-dollar',
        price:'53,117',
        title:'Old Meadowview Cottage',
        address:'112, Lavender Heights, Lal Kothi Scheme, Jaipur, Rajasthan',
    },
    {
        id:11,
        img: '/Images/Residence/img11.webp',
        icon:'fa-solid fa-dollar',
        price:'62,012',
        title:'Pinecrest Villa',
        address:'23, Palm Grove Apartments, Banjara Hills, Hyderabad, Telangana',
    },
    {
        id:12,
        img: '/Images/Residence/img12.webp',
        icon:'fa-solid fa-dollar',
        price:'65,761',
        title:'Lakeside Cottage',
        address:'49, Blue Ridge Towers, Wakad, Pune, Maharashtra',
    },
];

export default residenceData;